name: Deploy AsciiDoc to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout main branch
      uses: actions/checkout@v2
      with:
        ref: main

    - name: Install Asciidoctor
      run: |
        sudo apt-get update
        sudo apt-get install asciidoctor

    - name: Convert AsciiDoc to HTML
      run: |
        mkdir -p output
        for file in $(find . -name "*.adoc"); do
          asciidoctor -o output/$(basename "${file}" .adoc).html "$file"
        done

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./output
        destination_branch: gh-pages
